LABEL author="Kersten Breuer, Zeller Team, EMBL 2017" \
    maintainer="kersten-breuer@outlook.com"

FROM ubuntu:16.04

# Install essential unix packages and dependencies:
RUN apt-get update -y --fix-missing
RUN apt-get install -y build-essential \
    wget \
    unzip \
    tar \
    make \
    less \
    nano \
    nodejs \
    npm \
    git 
RUN apt-get update -y --fix-missing
# needed for cwltool, toil, Megahit:
RUN apt-get -y install python-dev \
    python-pip
# needed for ena_downloader:
RUN apt-get -y install python3
# needed for BBmap:
RUN apt-get -y install openjdk-8-jdk
# needed for Megahit:
RUN apt-get -y install zlib1g-dev \ 
    g++ \ 
    bc 


# Install cwl runners:
ENV TOIL_VERSION 3.10.1
#ENV CWLTOOL_VERSION 1.0.20171017195544
# as long as fix #554 is not in release: use directly from github
RUN cd /usr/local/ \
    && git clone https://github.com/common-workflow-language/cwltool.git \
    && cd cwltool \
    && pip install .

RUN pip install toil==${TOIL_VERSION}

# Install BBMap:
ENV BBMAP_URL http://downloads.sourceforge.net/project/bbmap/BBMap_36.28.tar.gz
RUN cd /usr/local/ \
    && wget -O bbmap.tar.gz ${BBMAP_URL} \
    && tar -xvzf bbmap.tar.gz \
    && rm bbmap.tar.gz
ENV PATH="/usr/local/bbmap:${PATH}"

# Install Megahit:
ENV MEGAHIT_URL https://github.com/voutcn/megahit/archive/v1.1.2.tar.gz
RUN cd /usr/local/ \
    && wget -O megahit.tar.gz ${MEGAHIT_URL} \
    && tar -xvzf megahit.tar.gz \
    && rm megahit.tar.gz \
    && mv megahit* megahit \
    && cd megahit \
    && make
ENV PATH="/usr/local/megahit/:${PATH}"

# Install Kraken:
ENV KRAKEN_URL http://ccb.jhu.edu/software/kraken/dl/kraken-1.0.tgz
RUN cd /usr/local/ \
    && wget -O kraken.tgz ${KRAKEN_URL} \
    && tar -xvzf kraken.tgz  \
    && rm kraken.tgz \
    && mv kraken* kraken \
    && cd kraken \
    && bash install_kraken.sh .
ENV PATH="/usr/local/kraken/:${PATH}"

## Install FastqQC:
ENV FASTQC_URL http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip
RUN cd /usr/local/ \
	&& wget ${FASTQC_URL} \
	&& unzip fastqc*.zip \
	&& rm -rf fastqc*.zip \
	&& cd FastQC \
	&& chmod a+x fastqc
ENV PATH="/usr/local/FastQC:${PATH}"

## Install MultiQC:
ENV MULTIQC_VERSION 1.3
RUN pip install multiqc==${MULTIQC_VERSION}

WORKDIR /data
CMD ["bash"]